helloapp:

  saying: ${HELLOAPP_SAYING:-Привет!}

greeter:

  saying: ${GREETER_SAYING:-Привет от Dropwizard}
  host: ${GREETER_BACKEND_HOST:-localhost}
  port: ${GREETER_BACKEND_PORT:-8081}

server:

  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 9001